/********************** N O T I C E****************************
 * Function translateType is defined in phase2.c to get rid of duplicated symbol error.
 **************************************************************/
/*********************************
 * File name:phase2.h
 * Purpose: Read the input file and use the core function
 *          namely, translateType(difined in phase2.c), to translated every line
 *          to machine code.
 *          Take filename and table(generated by phase1) as input,
 *          using that table to check the label and address for command
 *          like bne, j, etc. Then generated a output file named "output.txt".
 **********************************/

#ifndef PHASE2_H
#define PHASE2_H

/**************************
 * Function: getReg
 * Purpose: Get the corresponding binary code for a Register(e.g. $a0)
 *          Take the arg as parameter and return a five-bit binary string.
 **************************/
char *getReg(const char *arg);


/**************************
 * Function: getNum
 * Purpose: Get the corresponding binary code for a number(0 to 31)
 *          This function was designed in the start of the whole project to
 *          translate the shift amount. Thus, it can only generated 5-bit binary code.
 *          This function is subsitutable by decimalToBinary which was defined below.
 **************************/
char *getNum(const char *num);



/**************************
 * Function: decimalToBinary
 * Purpose: Get a "bit"-bit binary representation of a positive number less than 64.
 *          Pass number n and how many bit you need to the function. Then it will return
 *          a binary code in "bit" lenth. The adventage of it is you can get diffrenent lenth
 *          of binary ode.
 * Mention: Can also deal with negative number.
 **************************/
char *decimalToBinary(int n, int bit);

#endif // PHASE2_H
